SELECT 
    c.CAR_ID, 
    c.CAR_TYPE, 
    FLOOR(c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
    AND c.CAR_ID NOT IN (SELECT c.CAR_ID FROM CAR_RENTAL_COMPANY_CAR c 
                       LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
                       WHERE h.START_DATE <= '2022-11-30' AND h.END_DATE >= '2022-11-01' AND h.START_DATE IS NOT NULL
                      GROUP BY c.CAR_ID)
    AND c.DAILY_FEE * 30 * (100 + p.DISCOUNT_RATE) / 100 >= 500000
    AND c.DAILY_FEE * 30 * (100 + p.DISCOUNT_RATE) / 100 < 2000000
    AND p.DURATION_TYPE = '30일 이상'
GROUP BY CAR_ID    
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC