SELECT u.USER_ID, 
u.NICKNAME, 
CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS '전체주소', 
CONCAT(MID(u.TLNO, 1, 3), '-', MID(u.TLNO, 4, 4), '-', MID(u.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
GROUP BY u.USER_ID HAVING COUNT(*) >= 3
ORDER BY b.WRITER_ID desc