SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(SUM(r.REVIEW_SCORE) / COUNT(r.REVIEW_SCORE) * 100 / 100, 2) AS SCORE
FROM REST_INFO i
INNER JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID
ORDER BY SCORE DESC, i.FAVORITES DESC
# 5, 4.5, 5, 4.29