SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, u.GENDER, COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO u
INNER JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID 
WHERE u.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(o.SALES_DATE, '%Y-%m'), u.GENDER
ORDER BY YEAR, MONTH, u.GENDER