SELECT CAR_ID,
IF(
    IF(SUM(START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') > 0, 1, 0)=1,
    '대여중',
    '대여 가능'
) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC