SELECT HISTORY_ID,
CASE
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) < 7 THEN FLOOR((DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE)
    ELSE FLOOR((DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE * (100 - p.DISCOUNT_RATE) / 100)
END AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE AND
CASE 
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN DURATION_TYPE = '90일 이상'
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN DURATION_TYPE = '30일 이상'
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN DURATION_TYPE = '7일 이상'
    ELSE DURATION_TYPE = '7일 이상'
END
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC


# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR c
# RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
# INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE