SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY = '과자'OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유')
AND PRICE in (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY )
GROUP BY CATEGORY
ORDER BY PRICE DESC

